export const GET_CART_PRODUCT = 'GET_CART_PRODUCT';

export const ADD_CART_PRODUCT = 'GET_CART_PRODUCT';
export const DELETE_CART_PRODUCT = 'GET_CART_PRODUCT';
export const UPDATE_CART_PRODUCT = 'GET_CART_PRODUCT';